// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4Q_zF3-Mndw-pWmAlAE1Kdjbm-7XCb0',
    appId: '1:192089677138:web:13b7d8d2b46df73a482e8b',
    messagingSenderId: '192089677138',
    projectId: 'chaudhary-colections',
    authDomain: 'chaudhary-colections.firebaseapp.com',
    storageBucket: 'chaudhary-colections.firebasestorage.app',
    measurementId: 'G-1DV1NMN36K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mqRolWIIPXbYkbh53OpAYZakpKtJHp0',
    appId: '1:192089677138:android:fedd3db59e495edc482e8b',
    messagingSenderId: '192089677138',
    projectId: 'chaudhary-colections',
    storageBucket: 'chaudhary-colections.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-4BJImA3kxw-0wloG_c9IV9RPGHvT3M4',
    appId: '1:192089677138:ios:bb0467c12bcce73b482e8b',
    messagingSenderId: '192089677138',
    projectId: 'chaudhary-colections',
    storageBucket: 'chaudhary-colections.firebasestorage.app',
    iosBundleId: 'com.example.chaudharyCollections',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-4BJImA3kxw-0wloG_c9IV9RPGHvT3M4',
    appId: '1:192089677138:ios:bb0467c12bcce73b482e8b',
    messagingSenderId: '192089677138',
    projectId: 'chaudhary-colections',
    storageBucket: 'chaudhary-colections.firebasestorage.app',
    iosBundleId: 'com.example.chaudharyCollections',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4Q_zF3-Mndw-pWmAlAE1Kdjbm-7XCb0',
    appId: '1:192089677138:web:1c1816720c1be155482e8b',
    messagingSenderId: '192089677138',
    projectId: 'chaudhary-colections',
    authDomain: 'chaudhary-colections.firebaseapp.com',
    storageBucket: 'chaudhary-colections.firebasestorage.app',
    measurementId: 'G-FB0PYKRCNK',
  );
}
